assume-fixed:
  comment: >
    :wave: @{issue-author}, thanks for reporting an issue!


    This issue is assumed to be fixed in the latest stable release. Please
    reopen in case you can still reproduce the issue with the latest stable
    release. You can find the latest stable release at
    https://github.com/muthur-command/operating-system/releases/latest
  close: true
  close-reason: not planned

core-issue:
  comment: >
    :wave: @{issue-author}, thanks for reporting an issue!


    It looks like this issue is related to MC backend services. Please check
    the [mc_bd](https://github.com/muthur-command/mc_bd/issues)
    repository, the issue might have been reported already. Open a new issue
    in that repository if you can't find a matching issue.
  close: true
  close-reason: not planned

frontend-issue:
  comment: >
    :wave: @{issue-author}, thanks for reporting an issue!


    It looks like this issue is related to MC frontend services. Please
    check the [mc_fd](https://github.com/muthur-command/mc_fd/issues)
    repository, the issue might have been reported already. Open a new issue
    in that repository if you can't find a matching issue.
  close: true
  close-reason: not planned

supervisor-issue:
  comment: >
    :wave: @{issue-author}, thanks for reporting an issue!


    It looks like this issue is related to MCIO Supervisor. Please
    check the [supervisor](https://github.com/muthur-command/supervisor/issues)
    repository, the issue might have been reported already. Open a new issue
    in that repository if you can't find a matching issue.
  close: true
  close-reason: not planned

new-feature:
  comment: >
    :wave: @{issue-author}, thanks for your input!

    We use this issue tracker to track issues of currently supported features.
    Your request appears to request a new feature. We track potential new
    features in the [project discussions](https://github.com/orgs/muthur-command/discussions).
    Please check if someone already requested a similar feature, or create
    a new feature request with the "mcos" tag there. Thank you!
  close: true
  close-reason: not planned
