name: Release Drafter

on:
  push:
    branches:
      - mc
      - rel-*

jobs:
  update_release_draft:
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
      pull-requests: read  # for release-drafter/release-drafter to read PR content and labels
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@c345907820e0396f6f44bcfd9ac4763325f8feb0 # v7.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
